services:
  app:
    image: customer-app:1.0
    container_name: customer-app-uat
    restart: unless-stopped
    environment:
      APP_VERSION: "1.0"
      APP_ENVIRONMENT: UAT
      DB_HOST: customer-db-uat
      POSTGRES_DB: customer
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer123
    depends_on:
      db: {condition: service_healthy}
    ports: ["8082:8080"]
    networks: [customer-uat-net]
  db:
    image: postgres:16-alpine
    container_name: customer-db-uat
    restart: unless-stopped
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer123
    volumes: [customer-db-uat-data:/var/lib/postgresql/data]
    networks: [customer-uat-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customer -d customer"]
      interval: 5s
      timeout: 5s
      retries: 20
networks:
  customer-uat-net: {name: customer-uat-net, driver: bridge}
volumes:
  customer-db-uat-data: {name: customer-db-uat-data}
